jar 'com.ning.billing:killbill-api', '0.7.2-SNAPSHOT'
jar 'com.ning.billing.plugin:killbill-plugin-api-notification', '0.5.1-SNAPSHOT'
jar 'com.ning.billing.plugin:killbill-plugin-api-payment', '0.5.1-SNAPSHOT'
jar 'com.ning.billing.plugin:killbill-plugin-api-currency', '0.5.1-SNAPSHOT'
jar 'com.ning.billing:killbill-util:tests', '0.6.18-SNAPSHOT'
jar 'javax.servlet:javax.servlet-api', '3.0.1'
